---

- name: standalone-cinder-apb playbook to provision the application
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansibleplaybookbundle.asb-modules
  - role: ansible-role-k8s-standalone-cinder
  vars:
    apb_action: deprovision
